version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/sdp/localstack/data
      - AWS_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=dummyKey
      - AWS_SECRET_ACCESS_KEY=dummySecret
    volumes:
      - "./src/test/resources/localstack:/localstack"

networks:
  default:
    external:
      name: gsglobal